#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-11-2 обнГ4:11:01
# Module:      testTool
# Author:      xiaohai
# Revision:    $Id: Makefile 2544 2012-11-23 03:23:46Z zhenghb $
# Description: Makefile for testGetopt
#

include $(POCO_BASE)/build/rules/global


#BINPATH=./bin

objects = testTool

target         = testTool
target_version = 
target_libs    = 

include $(POCO_BASE)/build/rules/exec
