#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-7 IONg11:51:33
# Module:      Partner
# Author:      QuZhaojing
# Revision:    $v1.0$
# Description: Makefile for Partner
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main grid

target         = Grid
target_version = 1.0
target_libs    = active psutil

include $(POCO_BASE)/build/rules/exec

