#
#Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-11 OBNg5:30:58
# Module:      ServGridRel
# Author:      Zhaojing Qu
# Revision:    $v1.0$
# Description: Makefile for ServGridRel
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main

target         = ServGridRel
target_version = 1.0
target_libs    = psutil

include $(POCO_BASE)/build/rules/exec

