#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-8 IONg10:12:34
# Module:      AddressServRel
# Author:      Zhaojing Qu
# Revision:    $1.0$
# Description: Makefile for AddressServRel
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main  address_serv_rel

target         = AddressServRel
target_version = 1.0
target_libs    = active psutil

include $(POCO_BASE)/build/rules/exec

