#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-7 OBNg4:52:42
# Module:      Payment
# Author:      Zhaojing Qu
# Revision:    $v1.0$
# Description: Makefile for Payment
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main payment

target         = Payment
target_version = 1.0
target_libs    = active psutil

include $(POCO_BASE)/build/rules/exec

