#
# Makefile
#
# $Id: Makefile 1736 2012-10-26 01:51:20Z zhenghb $
#
# Makefile for db  project
#


include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle


INCDIR=$(SETTLEDIR)/src/shell/include
JSINCLUDEDIR=$(SETTLEDIR)/src/app/share
POCO_ADD_INCLUDE+=$(INCDIR1) $(INCDIR) $(INCDIR)/public $(INCDIR)/public/Process $(INCDIR)/public/table \
	$(INCDIR)/public/stl_hash $(INCDIR)/public/rapidxml $(INCDIR)/public/InfoData $(INCDIR)/business/psomc \
	$(JSINCLUDEDIR)/newcommonlib/include $(JSINCLUDEDIR)/newcommonmemory/include $(JSINCLUDEDIR)/newpluginengine/include \
        $(SETTLEDIR)/src/app/project/mdrpt/include

#POCO_ADD_LIBRARY +=$(SETTLEDIR)/src/app/project/mdrpt/lib64

objects = AccessMem Classify PrepCommon DealFile MainFlow
#objects = AccessMem_clue Classify PrepCommon DealFile_clue MainFlow 


target         = jsserviceprep
target_version = 1.0
target_libs    = newcommon newcommonmemory newpluginengine dr_api
target_libs_shell = public process 

# api hp libmdrapi_node.hp.so
#ib libmdrapi_node.ibm.so
ifeq ($(findstring HP-UX,$(POCO_CONFIG)),HP-UX)
USERLIBS += -lmdrapi_node.HP-UX
else ifeq ($(findstring AIX,$(POCO_CONFIG)),AIX)
USERLIBS += -lmdrapi_node.AIX -liconv
else
$(error this platform is not suppored.)
endif

include $(POCO_BASE)/build/rules/exec
