#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-7 OBNg2:53:51
# Module:      ServTerminal
# Author:      Zhaojing Qu
# Revision:    $v1.0$
# Description: Makefile for ServTerminal
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main

target         = ServTerminal
target_version = 1.0
target_libs    = psutil

include $(POCO_BASE)/build/rules/exec

