#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-12 IONg9:34:06
# Module:      ChannelEquipRel
# Author:      Zhaojing Qu
# Revision:    $v1.0$
# Description: Makefile for ChannelEquipRel
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main

target         = ChannelEquipRel
target_version = 1.0
target_libs    = psutil

include $(POCO_BASE)/build/rules/exec

