#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-11 OBNg4:50:34
# Module:      AddressPartyRel
# Author:      Zhaojing Qu
# Revision:    $v1.0$
# Description: Makefile for AddressPartyRel
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main calc_result_detail1

target         = CalcResultDetail
target_version = 1.0
target_libs    = psutil

include $(POCO_BASE)/build/rules/exec