#
# Makefile
#
# $Id: //poco/1.3/Foundation/Makefile#7 $
#
# Makefile for db  project
#


include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

objects = dbchecktool

target         = petriTool
target_version = 1.0
target_libs    = psutil dbutil PocoFoundation

include $(POCO_BASE)/build/rules/exec


