CXX_COMPILER=aCC
COMPILE_THREAD_FLAG=-mt -lpthread

#choose target platform: _WINDOWS | _SUNOS | _HPOS | _UNIXWARE | _LINUXOS
#choose target compiler: _MS_VC | _SUN_CC | _HP_ACC | _UW_CC

#PLATFORM_COMPILE_FLAG=-D_HPOS -D_HP_ACC  -AA -mt -lpthread# -D_RWSTD_MULTI_THREAD
#PLATFORM_LINK_FLAG=  -AA -g 

PLATFORM_COMPILE_FLAG=-D_HPOS -D_HP_ACC -D__ia64=1 +DD64  +u1 -D_XOPEN_SOURCE_EXTENDED -g -AA -mt -lpthread -w
PLATFORM_LINK_FLAG=-g +DD64  +u1 -D_XOPEN_SOURCE_EXTENDED -AA -g -w

ARCHIVE = ar
ARCHIVE_FLAG = -r
ARCHIVE_O_SYM = 
