CXX_COMPILER=CC
COMPILE_THREAD_FLAG=-mt -lthread -D_POSIX_PTHREAD_SEMANTICS
COMPILE_IOSTREAM_FLAG=-library=iostream
LEX_COMPILER=CC
ARCHIVE=CC
ARCHIVE_FLAG=$(COMPILE_IOSTREAM_FLAG) -xar 
ARCHIVE_O_SYM=-o
LIBDIR=lib32

#choose target platform: _WINDOWS | _SUNOS | _HPOS | _UNIXWARE
#choose target compiler: _MS_VC | _SUN_CC | _HP_ACC | _UW_CC

PLATFORM_COMPILE_FLAG=-D_SUNOS -D_SUN_CC -D_LEX_CXX -D_POSIX_PTHREAD_SEMANTIC -xarch=v8
PLATFORM_LINK_FLAG=
