#
# Makefile
#
# $Id: Makefile 1736 2013-03-07 12:00:20Z hed $
#
# Makefile for db  project
#


include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle


INCDIR=$(SETTLEDIR)/src/shell/include
JSINCLUDEDIR=$(SETTLEDIR)/src/app/share
POCO_ADD_INCLUDE+=$(INCDIR1) $(INCDIR) $(INCDIR)/public 

objects = main 


target         = cipher
target_version = 1.0
target_libs    = util 
target_libs_shell = 


include $(POCO_BASE)/build/rules/exec


