#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-8 OBNg12:21:05
# Module:      AcctItemType
# Author:      Zhaojing Qu
# Revision:    $v1.0$
# Description: Makefile for AcctItemType
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main

target         = AcctItemType
target_version = 1.0
target_libs    = psutil

include $(POCO_BASE)/build/rules/exec

