#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-7 IONg11:51:33
# Module:      Partner
# Author:      Administrator
# Revision:    $Id: Makefile 1736 2012-10-26 01:51:20Z zhenghb $
# Description: Makefile for Partner
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main partner

target         = Partner
target_version = 1.0
target_libs    = active psutil

include $(POCO_BASE)/build/rules/exec
