#
# Makefile
#
# $Id: Makefile 1736 2012-10-26 01:51:20Z zhenghb $
#
# Makefile for db  project
#


include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

objects = main terminal_regist 


target         = TerminalRegist
target_version = 1.0
target_libs    = active


include $(POCO_BASE)/build/rules/exec
