#
#Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-12 IONg10:05:45
# Module:      ShmAdmin
# Author:      Zhaojing Qu
# Revision:    $Id: Makefile 1736 2012-10-26 01:51:20Z zhenghb $
# Description: Makefile for ShmAdmin
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main

target         = psbshm
target_version = 1.0
target_libs    = psutil

include $(POCO_BASE)/build/rules/exec