#
# Copyright (c) 2009-2012 GUANGDONG ESHORE TECHNOLOGY CO., LTD.
# All rights reserved.
#
# Created:     2012-9-11 OBNg8:07:33
# Module:      SimCardPartyRel
# Author:      Zhaojing Qu
# Revision:    $v1.0$
# Description: Makefile for SimCardPartyRel
#

include $(POCO_BASE)/build/rules/global
include $(POCO_BASE)/build/rules/oracle

#BINPATH=./bin

objects = main

target         = SimCardPartyRel
target_version = 1.0
target_libs    = psutil

include $(POCO_BASE)/build/rules/exec

